version: "3"
services:
        fpm:
         build:
           context: ./build/php
           dockerfile: Redis
         image: php:7.4-fpm-alpine
         container_name: fpm
         volumes:
            - ./web:/php
            - ./conf/php/php-fpm.d:/usr/local/etc/php-fpm.d
            - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./conf/php/php.ini:/usr/local/etc/php/php.ini
         networks:
            lnmpnet:
              ipv4_address: 192.168.20.3
        nginx: 
         image: nginx:1.17.6-alpine 
         container_name: nginx
         ports:
           - 80:80
           - 443:443
         volumes:
           - ./conf/nginx/conf.d:/etc/nginx/conf.d
           - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
           - ./web:/usr/share/nginx/html:rw
           - ./logs/nginx:/var/log/nginx:rw
         networks:
            lnmpnet:
              ipv4_address: 192.168.20.4
        mysql:
         image: mysql:5.7
         container_name: mysqld
         ports: 
           - 3306:3306
         volumes:
            - ./mysqldata:/var/lib/mysql
            - ./conf/mysql/conf.d:/etc/mysql/conf.d
         environment:
            MYSQL_ROOT_PASSWORD: 123456
         networks:
            lnmpnet:
                ipv4_address: 192.168.20.5
        redis:
         image: redis:5.0-alpine
         container_name: redis
         ports: 
            - 6379:6379
         volumes:
            - ./redisdata:/data
            - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
         networks:
            - lnmpnet
networks:
        lnmpnet:
          driver: bridge
          ipam:
            config:
               - subnet: 192.168.20.0/24
